name: Deploy to Test

on:
  workflow_dispatch:

jobs:
  shopyfikTest:
    name: shopyfik test
    runs-on: ubuntu-latest
    needs: Build & Test

    environment:
      name: shopyfik test
      url:
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v1
