name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  shopyfikProd:
    name: shopyfik prod
    runs-on: ubuntu-latest

    environment:
      name: shopyfik prod
      url:
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v1
